apiVersion: serving .kserve.io/V1beta1
kind: InferenceService
metadata:
  name: kidney_disease_prediction
spec: 
  predictor:
    minReplicas: 1
    maxReplicas: 3
    containers:
     - name: kidney_disease_prediction
       image: 489857930967.dkr.ecr.ap-south-1.amazonaws.com/kidney_disease_prediction:latest
       resources:
         requests:
          cpu: "500m"
          memory: "1Gi"